SO: bash script logging: RCS ICD update
Updated bicas.conf

modified:   ../config/bicas.conf
modified:   bicas

diff --git a/mission/solar_orbiter/bicas/roc/bicas b/mission/solar_orbiter/bicas/roc/bicas
--- a/mission/solar_orbiter/bicas/roc/bicas
+++ b/mission/solar_orbiter/bicas/roc/bicas
@@ -60,7 +60,7 @@
 
 # Search pattern that determines which stdout (in particular from MATLAB) that is actually piped to stdout.
 # NOTE: This pattern must match the corresponding prefix used in MATLAB.
-declare -r STDOUT_PATTERN='^STDOUT: '    # NOTE: Regex. Includes "^" = beginning of line.
+declare -r STDOUT_PREFIX='STDOUT: '    # NOTE: Not regex. Implicit that should match beginning of line.
 
 # Prefix added to stdout when it is added to the log.
 declare -r STDERR_PREFIX='STDERR: '   # NOTE: Not a regex (but code will misbehave for regex commands)!
@@ -81,10 +81,11 @@ declare -r INNER_IRFUMATLAB_RELATIVE_PATH="lib/irfu-matlab"    # Needed to detec
 declare -r OUTER_IRFUMATLAB_RELATIVE_PATH="../../.."
 
 # Error codes for errors that do not occur in MATLAB.
-declare -r ERROR_CODE_CAN_NOT_FIND_LOG_DIR=2
-declare -r ERROR_CODE_CAN_NOT_WRITE_LOG_FILE=3
-declare -r ERROR_CODE_CAN_NOT_FIND_CONFIG_FILE=4
-declare -r ERROR_CODE_MATLAB_COMMAND_FILE_NOT_EXECUTABLE=5
+# Error code must always be 1. /RCS ICD 00037, iss1/rev2, draft 2019-07-11, Section 3.4.3.
+declare -r ERROR_CODE_CAN_NOT_FIND_LOG_DIR=1
+#declare -r ERROR_CODE_CAN_NOT_WRITE_LOG_FILE=1
+declare -r ERROR_CODE_CAN_NOT_FIND_CONFIG_FILE=1
+declare -r ERROR_CODE_MATLAB_COMMAND_FILE_NOT_EXECUTABLE=1
 
 
 
@@ -98,164 +99,111 @@ do
     if [[ "${!i}" == "--log" ]]
     then
         let i=i+1
-        declare -r log_dir="${!i}"
+        log_file="${!i}"
     elif [[ "${!i}" == "--config" ]]               # NOTE: Hardcoded CLI option that is defined in RCS ICD.
     then
         let i=i+1
-        declare -r config_file_argument="${!i}"
+        config_file="${!i}"
     fi
 done
 
 
 
-
-
-
-
-#==============================================================================================
-# Find (absolute) paths by using the path to this executable + relative paths.
-#
-# ASSUMES: This executable is located under a subdirectory of $BICAS_ROOT_PATH.
-#
-# NOTE: Some paths might not exist on disk and one can not use readlink on non-existent paths.
-#==============================================================================================
-temp=$(dirname "$0")/..
-declare -r BICAS_ROOT_PATH=$(readlink -f "$temp")
-declare -r DEFAULT_CONFIG_FILE="${BICAS_ROOT_PATH}/${DEFAULT_CONFIG_FILE_RELATIVE_PATH}"
-declare -r INNER_IRFUMATLAB_PATH=$(readlink -f "${BICAS_ROOT_PATH}/${INNER_IRFUMATLAB_RELATIVE_PATH}")  
-declare -r OUTER_IRFUMATLAB_PATH=$(readlink -f "${BICAS_ROOT_PATH}/${OUTER_IRFUMATLAB_RELATIVE_PATH}")
-
-# Set IRFUMATLAB_PATH : Path to irfu-matlab directory.
-# The value is selected depending on the directory structure used.
-if [[ -d "$INNER_IRFUMATLAB_PATH" ]] ; then
-    declare -r IRFUMATLAB_PATH="$INNER_IRFUMATLAB_PATH"
-else
-    declare -r IRFUMATLAB_PATH="$OUTER_IRFUMATLAB_PATH"
-fi
-
-
-
-
-
-
-
-#=====================================
-# Construct path and name of log file
-#=====================================
-if [[ ! -z "$log_dir" ]]
+#==================================================
+# Construct default log file if none was specified
+#==================================================
+if [[ -z "$log_file" ]]
 then
-    if [[ ! -d "$log_dir" ]] ; then
-        echo "Can not find specified log directory \"$log_dir\"." >> /dev/stderr
-        exit $ERROR_CODE_CAN_NOT_FIND_LOG_DIR
-    fi
-    base=$(basename "$0")
-    timestamp=$(date +%Y-%m-%d_%H.%M.%S)   # LOCAL time, not UTC.
-    log_file="${log_dir}/${base}_${timestamp}.log"
-    log_file_symlink="${log_dir}/${base}_latest.log"
-    
-    
-    
-    #=====================================================
-    # Test if can create (write) to the proposed log file
-    #=====================================================
-    touch "$log_file"
-    if [[ $? != 0 ]] ; then
-        echo "Can not write to log file \"$log_file\"." >> /dev/stderr
-        exit $ERROR_CODE_CAN_NOT_WRITE_LOG_FILE
-    fi
-
-
-
-    #=================================================================
-    # Create symlink to latest/current log.
-    # NOTE: This may technically be in violation of the RSC ICD 
-    # when removing/overwriting an old symlink.
-    # 
-    # test options:
-    #        -h FILE
-    #               FILE exists and is a symbolic link (same as -L)
-    # 
-    # ln options:
-    #        -r, --relative
-    #               create symbolic links relative to link location
-    #=================================================================
-    if [[ -h "$log_file_symlink" ]] ; then
-        rm -v "$log_file_symlink" >> "$log_file"
-    fi
-    ln -srv "$log_file" "$log_file_symlink" >> "$log_file"
-
-else
     log_file='/dev/null'
-fi
-
-
-
-#=======================
-# Determine config file
-#=======================
-if [[ -z "$config_file_argument" ]] ; then
-    # CASE: No config file argument set (or it is an empty string).
-    config_file="$DEFAULT_CONFIG_FILE"
 else
-    # CASE: Config file argument set.
-    # Canonical paths are useful for error messages/debugging on paths with symbolic links.
-    config_file=$(readlink -f "$config_file_argument")
-fi
-if [[ ! -f "$config_file" ]] ; then
-    echo "Can not find configuration file \"$config_file\"." >> /dev/stderr
-    exit $ERROR_CODE_CAN_NOT_FIND_CONFIG_FILE
+    log_file=$(readlink -f "$log_file")
 fi
 
 
 
-#==============================================
-# Read MATLAB_COMMAND setting from config file
-#==============================================
-# ASSUMES/NOTE: The syntax here must be in agreement with the MATLAB code.
-# IMPLEMENTATION NOTE: Needs some ~ugly code to handle the config file syntax, but should be quite flexible.
-# Uses "tail" to reduce multiple matches to one. NOTE: MATLAB code should give error for setting the same key multiple times.
-MATLAB_COMMAND_row_str=$(grep '^'"${MATLAB_COMMAND_SETTINGS_KEY}"' *= *"' "$config_file" | tail -n 1)      
-MATLAB_COMMAND=$(echo "$MATLAB_COMMAND_row_str" | awk -F '"' '{ print $2 }' | awk -F '"' '{ print $1 }' )
-# NOTE: Does not find any matching row. ==> Empty string ==> Must test for empty string before checking path.
 
-
-
-# ASSERTIONS: Test MATLAB_COMMAND
-# -z  String is empty
-if [[ -z "$MATLAB_COMMAND" ]] ; then
-    echo "Can not read setting MATLAB_COMMAND in configuration file \"$config_file\"." >> /dev/stderr
-    exit $ERROR_CODE_CAN_NOT_FIND_CONFIG_FILE
-fi
-# -f  File is a regular file (not directory, not symlink).
-# -x  File/directory has execute permission.
-# NOTE: If testing a symlink, then -f and -x test the pointed-to object.
-if [[ ! -f "$MATLAB_COMMAND" ]] || [[ ! -x "$MATLAB_COMMAND" ]] ; then
-    echo "\"${MATLAB_COMMAND_row_str}\" in configuration file \"$config_file\" does not refer to an executable file." >> /dev/stderr
-    echo "MATLAB_COMMAND=\"${MATLAB_COMMAND}\"" >> /dev/stderr
-    exit $ERROR_CODE_MATLAB_COMMAND_FILE_NOT_EXECUTABLE
-fi
-
-
-
-# DEBUG: Always piped to the actual stdout (in violation of RCS ICD). Useful for debugging.
-#echo log_dir           = "$log_dir"
-#echo log_file          = "$log_file"
-#echo log_file_symlink  = "$log_file_symlink"
-#echo "BICAS_ROOT_PATH  = \"$BICAS_ROOT_PATH\""
-#echo "MATLAB_COMMAND   = \"$MATLAB_COMMAND\""
-#echo "IRFUMATLAB_PATH  = \"$IRFUMATLAB_PATH\""
-#echo "config_file      = \"$config_file\""
-#echo "log_file         = \"$log_file\""
-
-
-
-echo "Command-line arguments: $@" >> "$log_file"
 
 
 
 # NOTE: Any CALL to this function should appropriately pipe stdout and stderr to log file.
-# Therefore code inside of it does not need to do this.
-launch_matlab_code() {
+#       Therefore code inside of it does not need to do this. This function effectively exists
+#       to make logging easier and should contain an as large fraction of the this script as possible.
+loggable_main_code() {
+
+    echo "Command-line arguments: $@"
+
+
+
+    #==============================================================================================
+    # Find (absolute) paths by using the path to this executable + relative paths.
+    #
+    # ASSUMES: This executable is located under a direct subdirectory to $BICAS_ROOT_PATH.
+    #
+    # NOTE: Some paths might not exist on disk and one can not use readlink on non-existent paths.
+    #==============================================================================================
+    local temp=$(dirname "$0")/..
+    local  BICAS_ROOT_PATH=$(readlink -f "$temp")
+    local  DEFAULT_CONFIG_FILE="${BICAS_ROOT_PATH}/${DEFAULT_CONFIG_FILE_RELATIVE_PATH}"
+    local INNER_IRFUMATLAB_PATH=$(readlink -f "${BICAS_ROOT_PATH}/${INNER_IRFUMATLAB_RELATIVE_PATH}")  
+    local OUTER_IRFUMATLAB_PATH=$(readlink -f "${BICAS_ROOT_PATH}/${OUTER_IRFUMATLAB_RELATIVE_PATH}")
+
+    # Set IRFUMATLAB_PATH : Path to irfu-matlab directory.
+    # The value is selected depending on the directory structure used.
+    if [[ -d "$INNER_IRFUMATLAB_PATH" ]] ; then
+        local IRFUMATLAB_PATH="$INNER_IRFUMATLAB_PATH"
+    else
+        local IRFUMATLAB_PATH="$OUTER_IRFUMATLAB_PATH"
+    fi
+
+
+
+    #======================================================
+    # Determine config file
+    # NOTE: Requires DEFAULT_CONFIG_FILE to have been set.
+    #======================================================
+    if [[ -z "$config_file" ]] ; then
+        # CASE: No config file argument set (or it is an empty string).
+        config_file="$DEFAULT_CONFIG_FILE"
+    else
+        # CASE: Config file argument set.
+        # Canonical paths are useful for error messages/debugging on paths with symbolic links.
+        config_file=$(readlink -f "$config_file")
+    fi
+    if [[ ! -f "$config_file" ]] ; then
+        echo "Can not find configuration file \"$config_file\"." >> /dev/stderr
+        exit $ERROR_CODE_CAN_NOT_FIND_CONFIG_FILE
+    fi
+
+
+
+    #==============================================
+    # Read MATLAB_COMMAND setting from config file
+    #==============================================
+    # ASSUMES/NOTE: The syntax here must be in agreement with the MATLAB code.
+    # IMPLEMENTATION NOTE: Needs some ~ugly code to handle the config file syntax, but it should be quite flexible.
+    # Uses "tail" to reduce multiple matches to one. NOTE: MATLAB code should give error for setting the same key multiple times.
+    MATLAB_COMMAND_row_str=$(grep '^'"${MATLAB_COMMAND_SETTINGS_KEY}"' *= *"' "$config_file" | tail -n 1)      
+    MATLAB_COMMAND=$(echo "$MATLAB_COMMAND_row_str" | awk -F '"' '{ print $2 }' | awk -F '"' '{ print $1 }' )
+    # NOTE: Does not find any matching row. ==> Empty string ==> Must test for empty string before checking path.
+
+
+
+    # ASSERTIONS: Test MATLAB_COMMAND
+    # -z  String is empty
+    if [[ -z "$MATLAB_COMMAND" ]] ; then
+        echo "Can not read setting MATLAB_COMMAND in configuration file \"$config_file\"." >> /dev/stderr
+        exit $ERROR_CODE_CAN_NOT_FIND_CONFIG_FILE
+    fi
+    # -f  File is a regular file (not directory, not symlink).
+    # -x  File/directory has execute permission.
+    # NOTE: If testing a symlink, then -f and -x test the pointed-to object.
+    if [[ ! -f "$MATLAB_COMMAND" ]] || [[ ! -x "$MATLAB_COMMAND" ]] ; then
+        echo "\"${MATLAB_COMMAND_row_str}\" in configuration file \"$config_file\" does not refer to an executable file." >> /dev/stderr
+        echo "MATLAB_COMMAND=\"${MATLAB_COMMAND}\"" >> /dev/stderr
+        exit $ERROR_CODE_MATLAB_COMMAND_FILE_NOT_EXECUTABLE
+    fi
+
+
 
     echo "BICAS_ROOT_PATH  = \"$BICAS_ROOT_PATH\""
     echo "MATLAB_COMMAND   = \"$MATLAB_COMMAND\""
@@ -317,8 +265,8 @@ launch_matlab_code() {
             addpath('${IRFUMATLAB_PATH}',      '-begin');\
             error_code = $MATLAB_SCRIPT_NAME($matlab_arg_list);\
             quit(error_code);\
-        catch e;\
-            msg = sprintf('Could not launch the MATLAB script. The reason MIGHT be that MATLAB could not find it.\nException message: %s\n', e.message);\
+        catch Exc;\
+            msg = sprintf('Could not launch the MATLAB script. The reason MIGHT be that MATLAB could not find it.\nException message: %s\n', Exc.message);\
             fprintf(1, msg);\
             fprintf(2, msg);\
             quit(1);\
@@ -334,6 +282,7 @@ launch_matlab_code() {
     else
         echo "Bash launch function: matlab_error_code = $matlab_error_code"    # NOTE: Send to stdout ==> Piped to log file.
     fi
+    
     
     
     # NOTE: "exit" inside a bash function does NOT EXIT the entire script file.
@@ -372,24 +321,29 @@ log_stderr() {
 
 
 
-if [[ -z "$log_dir" ]]
-then
-    # CASE: No log file specified.
-    
-    launch_matlab_code "$@"                      | grep "$STDOUT_PATTERN" | sed "s/${STDOUT_PATTERN}//"
-    matlab_error_code=${PIPESTATUS[0]}    # Get exit code of the first component of piping.
-else
-    # CASE: Log file specified.
-    
-    # Launch MATLAB and do nothing with stderr.
-    #launch_matlab_code "$@" | tee -a "$log_file" | grep "$STDOUT_PATTERN" | sed "s/${STDOUT_PATTERN}//"
-    
-    # Launch MATLAB and COPY stderr to the log file (where stderr is prefixed).
-    log_stderr "$log_file" launch_matlab_code "$@" | tee -a "$log_file" | grep "$STDOUT_PATTERN" | sed "s/${STDOUT_PATTERN}//"
-    
-    matlab_error_code=${PIPESTATUS[0]}    # Get exit code of the first component of piping.
-fi
+# Filter stdout so that only that intended to for stdout is let through.
+filter_out_stdout() {
+    # NOTE: Call grep to FILTER entire rows. Call sed to filter out the prefix. Must call both.
+    grep "^${STDOUT_PREFIX}" | sed "s/^${STDOUT_PREFIX}//"
+}
 
 
 
+#######################################
+# CALL BASH FUNCTION AND START LOGGING
+#######################################
+# Launch MATLAB and do nothing with stderr.
+#loggable_main_code "$@" | tee -a "$log_file" | filter_out_stdout
+
+# Launch MATLAB and COPY stderr to the log file (where stderr is prefixed)
+# ------------------------------------------------------------------------
+# tee options:
+#        -a, --append
+#               append to the given FILEs, do not overwrite
+#               
+# NOTE: Should always APPEND to log file.
+#       /RCS ICD 00037, iss1/rev2, draft 2019-07-11, Section 4.2.1
+log_stderr "$log_file" loggable_main_code "$@" | tee -a "$log_file" | filter_out_stdout
+
+matlab_error_code=${PIPESTATUS[0]}    # Get exit code of the first component of piping.
 exit $matlab_error_code
